### ISSUE TITLE
All issues(Server Setting Up) 

### ISSUE THREAD

**Issue by Mtuthuko** [noreplysims/VarsityOnline#2]
All Issues have been documented on Taiga.
screenshots of issues also added on the code section.

**Comment by Mtuthuko** [comment]
https://github.com/noreplysims/VarsityOnline/blob/master/ServerIssues.txt

**Comment by ZBOT3000** [comment]
![ ](https://github.com/noreplysims/VarsityOnline/blob/master/ServerIssue2.png)
